import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../../components/navbar";
import Footer from "../../components/footer";
// import useTranslation from "next-translate/useTranslation";

import createTranslation from "next-translate/createTranslation";
// import i18n from "../../../i18n";
// import { notFound } from "next/navigation";
// import { useLocale } from "next-intl";
// import { useTranslations } from "next-intl";
// import { getTranslations } from "next-intl/server";
const inter = Inter({ subsets: ["latin"] });
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { lang } = createTranslation("common");
  if (!i18n.locales.includes(lang)) {
    redirect(`/${i18n.defaultLocale}/${lang}`);
  }
  return (
    <html lang={lang} className="relative">
      <body className={`${inter.className} relative padding-x py-8`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
