import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/navbar";
import Footer from "./components/footer";
import createTranslation from "next-translate/createTranslation";
const inter = Inter({ subsets: ["latin"] });
import { redirect } from "next/navigation";
import { use } from "react";

const geti18nConf = () => import("i18n.json").then((module) => module.default);

export const metadata = {
  title: "Confident Feet",
  description: "Generated by Michael Anigboya",
};

export default function RootLayout({ children }) {
  const { lang } = createTranslation("common");
  const i18n = use(geti18nConf());

  if (!i18n.locales.includes(lang)) {
    redirect(`/${i18n.defaultLocale}/${lang}`);
  }
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
